try
	print('Hello try!')
	error('text exception')
catch (e)
	print('message:', e)
end
